name: 'Notification: Star'

on:
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  notification:
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on given a star
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_RECIPIENT }}
          token: ${{ secrets.TELEGRAM_BOT_API }}
          message: The ${{ github.actor }} user gave a star to the repository.
